name: YPPL_Inference

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3]
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - run: |
          from subprocess import call
          call(['julia', '-e',
                'using Pkg;'
                'Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"));'
                'Pkg.Registry.add(RegistrySpec(url = "https://github.com/yiyuezhuo/YYZRegistry.git"));'
                'Pkg.Registry.status()'])
        shell: python
      - uses: julia-actions/julia-runtest@master
      - run: |
          from subprocess import call
          call(['julia', '-e',
                'using Pkg;'
                'Pkg.activate("./test");'
                'Pkg.develop(PackageSpec(path="."));'
                'include("test/plots.jl");'])
        shell: python
